### PR TITLE
Remove useless styles

### PR DESCRIPTION
**Pull request by liubich**

### CODE REVIEW

**Comment by probil** [comment]
Your branches should be atomic. 
Current branch is not. It contains 2 changes:
- removes styles
- reformats js

It's not so bad while you are working alone or with 1-2 devs. But when team is bigger it takes a lot of time (and metal energy) to review. Creating small and focused branches helps a lot!

**Comment by liubich** [comment]
@probil, I didn't make any refactoring of JS. I just removed import of css from it. That changes was made by prettier, I think.
I will use this tool more carefull in future :relieved:

**Comment by liubich** [comment]
@probil, is it better now?

**Comment by probil** [comment]
Much better

**Comment by probil** [comment]
Have you read that already? https://medium.com/@sergiy.stotskiy/the-wisdom-of-splitting-task-into-subtasks-2c4b105f6b44

**Pull request merged**
